### PR TITLE
Upgrading Cmake, adding arm-none-eabi

### PR DESCRIPTION
**Pull request by thirtytwobits**
Upgrading Cmake to 3.30
Adding arm-none-eabi-gcc toolchains

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
@thirtytwobits did you mean do request a review?

**Comment by thirtytwobits** [comment]
Yes. Just making sure you are okay with this.

**Review by pavel-kirienko — APPROVED** [review]
This is fine but since you started adding different versions, why not add v13 as well

**Comment by thirtytwobits** [comment]
I added #51 to track updating gcc.

**Pull request merged**
